name: Merge multi-arch docker image

on:
  workflow_dispatch: 
  schedule:
    - cron: '0 1 * * *'

env:
  DOCKERHUB_REPO: hdbjlizhe/autman

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Get GitHub Release Tag
        id: get_tag
        run: |
          API_RESPONSE=$(curl -s "https://api.github.com/repos/hdbjlizhe/fanli/releases/latest")
          browser_download_url=$(echo "$API_RESPONSE" | jq -r '.assets[] | select(.name == "autMan_${{ matrix.architecture }}.tar.gz").browser_download_url')
          TAG_NAME=$(echo "$API_RESPONSE" | jq -r '.tag_name')
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          echo "browser_download_url=$browser_download_url" >> $GITHUB_ENV
          
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Get Docker Image Digest
         run: |
           DIGEST_AMD^$=$(docker inspect --format='{{index .RepoDigests 0}}' ${{ env.DOCKERHUB_REPO }}:${{ env.TAG_NAME }}-amd64)
           echo "DIGEST_AMD=$DIGEST_AMD" >> $GITHUB_ENV
           DIGEST_ARM^$=$(docker inspect --format='{{index .RepoDigests 0}}' ${{ env.DOCKERHUB_REPO }}:${{ env.TAG_NAME }}-arm64)
           echo "DIGEST_ARM=$DIGEST_ARM" >> $GITHUB_ENV

      - name: Create manifest for multi-arch image
        run: |
          docker manifest create temp-manifest ${{ DIGEST_AMD }} ${{ DIGEST_ARM }}
      - name: Annotate
        run: |
          docker manifest annotate temp-manifest ${{ env.DOCKERHUB_REPO }}:${{ env.TAG_NAME }}-amd64 --os linux --arch amd64
          docker manifest annotate temp-manifest ${{ env.DOCKERHUB_REPO }}:${{ env.TAG_NAME }}-arm64 --os linux --arch arm64

      - name: Push manifest for multi-arch image
        run: |
          docker manifest push ${{ env.DOCKERHUB_REPO }}:latest temp-manifest
